DataDog/dd-sdk-android-gradle-plugin

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
Ensure we use the flavor name and not the variant to match the tag sent by the SDK
> RUMM-1075 Use flavor name in the variant tag

- buildSrc/build.gradle.kts
Follow-up on #16 : one more place needs to be updated.
> Android Gradle Plugin 4.1.2 in buildSrc module

- docs/upload_mapping_file.md
fixed broken title and links to images
> fixed broken title and links to images

- docs/upload_mapping_file.md
A brief description of the change being made with this pull request.
> fixed code indentation

- .gitlab-ci.yml
- Dockerfile.gitlab
This PR adds a static analysis to ensure we don't use any non-inclusive language.
> Add language check for diversity and inclusion

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/ReflectUtils.kt
Following this reported [issue](https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/45) and after further investigations it seems that by doing:
```
variantCompileTasks.doLast { ... }
```
we were braking the `up-to-date` checks and therefore the incremental capability for the compilation tasks (the compile task was alway performed even if the code was not changed).
This PR proposes a new approach for the check dependency routine by introducing the new `CheckDepsTask` which will also take advantage of the task incremental capability (meaning that if the module configuration will not be changed this task will not be executed again).
> RUMM-1546 Introduce the CheckDepsTask

- LICENSE
For now the License is not recognised by Github License detection
> Update License to be recognised by Github 

- .gitlab-ci.yml
- README.md
- dd-sdk-android-gradle-plugin/build.gradle.kts
- samples/basic/build.gradle
Setup the project to publish automatically on Gradle Portal
> RUMM-1778 publish on Gradle Portal

- README.md
- docs/upload_mapping_file.md
update documentation for Gradle plugin
> RUMM-1778 update documentation for Gradle plugin

- buildSrc/src/main/kotlin/com/datadog/gradle/config/CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
Add a changelog and update the plugin version
> Prepare publishing Gradle Plugin 1.2.0

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/build.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/GitUtils.kt
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_disabled.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_set_to_warn.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/build_without_datadog_dep.gradle.kts
- dd-sdk-android-gradle-plugin/src/test/resources/lib_module_build.gradle.kts
- gradle/libs.versions.toml
In this PR we are adding functional tests for the Datadog Gradle Plugin:
- testing `assemble` task with and without the `--build-cache` option
- testing `assemble` task with and without the `--configuration-cache` option
- testing `upload` task for all the flavours
- testing the plugin configuration options
> RUMM-1814 Provide functional tests for Datadog Gradle plugin

- gradle/libs.versions.toml
> Update to version 1.12.0-alpha2

- gradle/libs.versions.toml
> Update to version 1.12.0-beta1

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
- dd-sdk-android-gradle-plugin/transitiveDependencies
- gradle/libs.versions.toml
Upgrade the OkHttp dependency to use the last available API
> RUMM-2087 upgrade okhttp

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- samples/variants/build.gradle
> Prepare publishing plugin 1.3.0

- README.md
> Update documentation to mention deobfuscation is only for RUM

- gradle/libs.versions.toml
> Update to version 1.12.0-rc1

- gradle/libs.versions.toml
> Update to version 1.13.0-beta1

- CHANGELOG.md
- README.md
- samples/variants/build.gradle
Preparation for upcoming 1.4.0 release, this change merges content of `release/1.3.0` branch into `develop`.
> Merge release/1.3.0 branch into develop

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
Update changelog and version for the version 1.4.0 release.
> RUMM-2209: Prepare version 1.4.0 release

- CHANGELOG.md
This change merges `release/1.4.0` branch into `develop`.
> Merge release/1.4.0 branch into develop

- gradle/libs.versions.toml
> Update to version 1.13.0-rc1

- gradle/libs.versions.toml
> Update to version 1.13.0

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.13.0 to version 1.14.0-beta1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.13.0...1.14.0-beta1)
> Update to version 1.14.0-beta1

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/ApiKey.kt
Following a change made in #106 add a missing copyright to the new file added in #104.
> Add missing copyright

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
A brief description of the change being made with this pull request.
> Prepare 1.5.0 release

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
Prepare a new release `1.5.1`.
> Prepare a new release

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.14.0-beta2 to version 1.14.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.14.0-beta2...1.14.0)
> Update to version 1.14.0

- .gitlab-ci.yml
- CONTRIBUTING.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/BaseExtensionConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/config/DependencyUpdateConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/config/JacocoConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/config/JavadocConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/CheckThirdPartyLicensesTask.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/SPDXLicense.kt
- buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesPlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/VariantIteratorTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/ReflectUtils.kt
A brief description of the change being made with this pull request.
> Update ktlint to 0.47.1

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
This PR bumps Datadog SDK version to 1.15.0.
> Update Datadog SDK version to 1.15.0

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.16.0-beta1 to version 1.16.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.16.0-beta1...1.16.0)
> Update to version 1.16.0

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
> Next dev cycle

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- gradle/libs.versions.toml
This change prepares the release of version `1.6.0`.
> Prepare 1.6.0 release

- gradle/libs.versions.toml
This change bumps Android Gradle Plugin version to 7.4.0.
> Android Gradle Plugin 7.4.0

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This change fixes publishing (I hope) which was broken as the result of the `com.gradle.plugin-publish` plugin version bump to `1.1.0`. This new version auto-configures both signing and publishing (and this cannot be disabled).
So errors which were happening are:
> Cannot perform signing task ':dd-sdk-android-gradle-plugin:signDd-sdk-android-gradle-pluginPluginMarkerMavenPublication' because it has no configured signatory
This was happening because `com.gradle.plugin-publish` does signing auto-configuration in the `afterEvaluate` and its `afterEvaluate` was executing earlier than we do signing configuration, so I moved signing configuration out of `afterEvaluate`.
> Invalid publication 'pluginMaven': multiple artifacts with the identical extension and classifier ('jar', 'javadoc').
This …
> Fix publishing

- .gitlab-ci.yml
- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/build.gradle.kts
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- gradle/libs.versions.toml
This PR does the merge of 1.6.0 release into develop.
> Merge release 1.6.0 into develop

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.16.0 to version 1.17.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.16.0...1.17.0)
> Update to version 1.17.0

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
This change raises upload limit for US1 datacenter only to 100 MB (and bumps timeout to 60s for all DCs). This is temporary change, because once all DCs are able to support large uploads, this limits will be aligned.
> RUMM-3011: Raise upload limit to 100MB for US1 datacenter

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
This change bumps dev version to 1.8.0, considering the upcoming 1.7.0 release.
> Next dev version 1.8.0

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- gradle/libs.versions.toml
This PR prepares release 1.7.0.
> Prepare release 1.7.0

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DatadogSite.kt
Adds support to uploading mapping files to our AP1 site
> RUMM-3013 Add support to AP1

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.17.0 to version 1.17.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.17.0...1.17.1)
> Update to version 1.17.1

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DatadogSite.kt
Adds support to uploading mapping files to our Staging site
> RUMM-3063 add support for Staging upload

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
This change updates Datadog SDK to version 1.19.0
> Update Datadog SDK to 1.19.0

- .github/workflows/codeql-analysis.yml
This PR sets up CodeQL scan for the repo in the similar manner as it was done for `dd-sdk-android` repo earlier.
> RUMM-3260: Setup CodeQL scan

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
We are going to release `1.9.0`, so bumping version in the `develop` branch.
> Next dev cycle: 1.10.0

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This PR prepares release `1.9.0`.
> Prepare 1.9.0 release

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
This change updates SDK version to 1.19.1 after its release, and also updates plugin version for the sample apps to 1.9.0.
> Update SDK version to 1.19.1

- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- gradle/libs.versions.toml
Updating from version 1.19.1 to version 1.19.2: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.19.1...1.19.2)
> Update to version 1.19.2

- buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_disabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_set_to_warn.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/build_without_datadog_dep.gradle
- dd-sdk-android-gradle-plugin/src/test/resources/lib_module_build.gradle
- gradle/libs.versions.toml
- samples/basic/build.gradle
- samples/variants/build.gradle
Updating from version 1.19.2 to version 2.0.0-beta1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.19.2...2.0.0-beta1)
> Update to version 2.0.0-beta1

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This PR prepares release `1.10.0`.
> Prepare release 1.10.0

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/GitUtils.kt
Ensure we read the API Key from all documented sources
Fixes #184
> RUM-520 read DATADOG_API_KEY from gradle properties

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
This PR bumps dev version to `1.12.0`, because `1.11.0` is going to be released.
> Next dev iteration

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
This PR prepares release `1.11.0`.
> Prepare release 1.11.0

- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
This PR bumps dev version to `1.13.0` following https://github.com/DataDog/dd-sdk-android-gradle-plugin/pull/200
> Next dev version

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This PR prepares release `1.12.0` of Gradle Plugin.
> RUM-1957: Prepare release 1.12.0

- buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
Java agent wasn't attached to the tests run, because we are not using Android tests here, but just plain JVM tests.
> Fix CI visibility integration

- .github/CODEOWNERS
Update codeowners file to include `@DataDog/rum-mobile-android` team
> Update CODEOWNERS to include rum-mobile-android

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/DdAppIdentifier.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
As requested by the backend team, we will use `snake_case` for properties in the `event` form data.
> RUM-1822: Use snake case for properties in mapping file event

- CONTRIBUTING.md
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdNdkSymbolFileUploadTaskTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdTaskUtilsTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/RepositoryInfoTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/VariantIteratorTest.kt
This is needed to be able to update Kotlin version, see https://youtrack.jetbrains.com/issue/KT-60748.
> RUM-3487: Remove non-ASCII characters from test names

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
This PR updates AGP version to 8.3.1.
> Update AGP to 8.3.1

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdFileUploadTask.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
This PR merges changes from release 1.13.1 into `main` branch.
> Merge release `1.13.1` into `main` branch

- CHANGELOG.md
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdFileUploadTask.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
This PR merges changes from release 1.13.1 into `develop` branch.
> Merge release `1.13.1` into `develop` branch

- .gitlab-ci.yml
- buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
- dogfood.py
This PR adds dogfood script (the same as used in https://github.com/DataDog/dd-sdk-android repo) and also aligns runner tags to `arch:amd64` from the legacy `runner:main` or `runner:docker`.
> Add dogfood script

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This PR prepares release of the version `1.14.0`. See changelog for details.
> Prepare release 1.14.0

- CHANGELOG.md
This PR merges `release/1.14.0` branch into `develop` branch with all the conflicts resolved.
> Merge `release/1.14.0` branch into `develop` branch

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
This PR updates AGP version to 8.5.0.
> Update AGP version to 8.5.0

- .gitlab-ci.yml
Service account repo cannot access `ci.dd-sdk-android.*` namespace, so updating to the repo-specific namespace.
> Update Github token reference

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
This PR updates latest versions configuration for the functional tests.
> Update Gradle to 8.11.1, AGP to 8.7.2, Kotlin to 2.1.0 for the latest versions configuration for the functional tests

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
This PR updates the latest versions configuration used in the functional tests.
Note: not bumping Gradle to 8.12, because of the following regression https://github.com/gradle/gradle/issues/31942.
> AGP 8.8.0 for the latest configuration in the functional tests

- CHANGELOG.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
This PR prepares release 1.15.0 of the Datadog Android Gradle Plugin.
> Prepare release 1.15.0

- CHANGELOG.md
This PR does the merge of release 1.15.0 into `develop` branch.
> Merge release 1.15.0 into `develop` branch

- gradle/libs.versions.toml
This PR updates version of Datadog Gradle Plugin used in samples to 1.15.0.
> Update version of Datadog Gradle Plugin used in samples to 1.15.0

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/FileUploadTask.kt
Small improvement to log the message if there are no files to upload in the upload task.
> Log message if there are no files to upload

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
This PR updates Datadog SDK to 2.18.0.
> Update Datadog SDK to 2.18.0

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
This PR updates AGP to 8.8.2 in both buildscript and also in the latest test configuration.
> Update AGP to 8.8.2

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
This PR updates AGP version used to 8.9.0 both in the buildscript and in the latest functional test configuration.
> Update AGP to version 8.9.0

- .gitlab-ci.yml
- instrumented/build.gradle.kts
Prior to this PR, instrumented test was actually never run on CI, this PR fixes the gitlab CI configuration, and fully activate the kotlin compiler plugin in instrumented test.
> Fix gitlab-ci instrumented task

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
When testing with the sample app in dd-sdk-android, it throws build error with the plugin:
```
e: Multiple values are not allowed for plugin option com.datadoghq.kotlin.compiler:TRACK_VIEWS
Plugin "com.datadoghq.kotlin.compiler" usage:
TRACK_VIEWS <string>       Track Views
TRACK_ACTIONS <string>     Track Actions
RECORD_IMAGES <string>     Record Images
```
The reason is that the sample app is using `ksp` and `kapt` as plugin. it is a known issue that `kapt` and `ksp` have some problem with the usage of `freeCompilerArgs`:
https://youtrack.jetbrains.com/issue/KT-55452
https://youtrack.jetbrains.com/issue/KT-55565/Consider-de-duping-or-blocking-standard-addition-of-freeCompilerArgs-to-KaptGenerateStubsTask
So the way of fixing it is to filter out `KaptGenerateStubsTask` and `ksp` tasks …
> Filter out ksp and KaptGenerateStubsTask when applying freeCompilerArgs

- dd-sdk-android-gradle-plugin/transitiveDependencies
- gradle/libs.versions.toml
> Bump Kotlin version to 2.0.21

- LICENSE-3rdparty.csv
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DefaultPluginContextUtils.kt
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/IrExt.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
- dd-sdk-android-gradle-plugin/transitiveDependencies
- gradle/libs.versions.toml
Bump kotlin version and kotlin embeddable to 2.0.21
> Bump Kotlin version and Kotlin embeddable to 2.0.21

- .gitlab-ci.yml
- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/MappingFileUploadTask.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- gradle/libs.versions.toml
Merge develop to feature/kotlin-compiler-plugin
> Merge develop to feature/kotlin-compiler-plugin

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DefaultPluginContextUtils.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostCompilationTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagCompilationTest.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
- samples/lib-module/src/main/kotlin/com/datadog/android/compose/DatadogModifier.kt
- samples/lib-module/src/main/kotlin/com/datadog/android/compose/RecordImages.kt
- samples/lib-module/src/main/kotlin/com/datadog/android/compose/TrackViews.kt
This is a PR preparing for the real API in the `dd-sdk-android`, the real APIs should be in the package called `com.datadog.android.compose` instead of `kcp`
> Update the package name of instrumentation API

- README.md
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
- dd-sdk-android-gradle-plugin/transitiveDependencies
- gradle/libs.versions.toml
Merge develop into Feature/kotlin-compiler-plugin
> Merge develop into Feature/kotlin-compiler-plugin

- .gitlab-ci.yml
Fix instrumented test task timeout issue
> Fix instrumented test task timeout issue

- .github/workflows/codeql-analysis.yml
Ubuntu 20.04 is not supported anymore from yesterday, so this PR updates the version to latest, same as dd-sdk-android:
> Update codeql-analysis Ubuntu version from 20.04 to latest

- .github/chainguard/all.gitlab.pr.sts.yaml
Because we need first to push the branch with changes, but it requires write permission.
> RUM-10224: Allow content write for dd-sdk-android

- .gitlab-ci.yml
- Dockerfile.gitlab
Use new Ubuntu version for our CI.
> CS-71: Update base docker image to jammy

- dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
Bumping versions of tooling for the configuration in the functional test.
> Update latest build tooling versions config for the functional test

- build.gradle.kts
- buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
- ci/pipelines/default-pipeline.yml
This PR is similar to https://github.com/DataDog/dd-sdk-android/pull/2770, see more details there.
> RUM-10648: Migrate to Central Publisher portal

- dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
The indexing is broken on windows since 1.17.0-rc1, due to wrong jar path being provided by plugin
RUM-11769
> RUM-11769: Fix KCP wrong jar path for Windows

- CHANGELOG.md
A brief description of the change being made with this pull request.
> Merge release/1.21.0 into develop
