DataDog/dd-sdk-android-gradle-plugin

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt

Prevent creating upload tasks on non minified variants.
It will prevent having too many gradle tasks in the project, reducing the noise in the tasks list, and avoid creating a task that will do nothing because no corresponding mapping file exists.

RUMM-1059 Only apply task for minified variants

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt

Let customer disable the plugin to only analyse and create variants when necessary. 
Also delays the validation of API Key, allowing developers to have the plugin initialise on computers where the API Key is undefined.

RUMM-1058 Allow disabling the plugin

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtension.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt

This change makes variants property non-nullable to avoid force-casting (`variants!!`) in the build script.
Knowledge that force-casting is bad.
Solution looks a bit hacky. Better way is to do injection with `ObjectFactory` as described here https://docs.gradle.org/current/userguide/custom_gradle_types.html#collection_types, but the problem is that this method is incubating, so I guess it doesn't guarantee binary compatibility yet (although it is available since Gradle 5.5).

RUMM-1056: Make variants property non-nullable

---

build.gradle.kts
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
samples/basic/build.gradle

Increases the OkHttpClient call and write timeout to 45 seconds for the gradle task which uploads the proguard mapping file to Datadog endpoint.

RUMM-1055 Increase the OkHttpClient call/write timeout

---

README.md
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/SdkCheckLevel.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/MissingSdkException.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionConfigurationForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionForgeryFactory.kt
samples/variants/build.gradle

This changes build a link between Datadog SDK Gradle plugin and Datadog SDK itself: plugin will be able to notify the user if Datadog SDK is missing in the project dependencies (strictly speaking in the runtime classpath). This is achieved by introducing new `checkProjectDependencies` property of the plugin extension, which has 3 options: `none` - take no action if Datadog SDK is missing, `warn` - log a warning if Datadog SDK is missing, `fail` - fail the build if Datadog SDK is missing. This property can be applied either on the global level or per flavor:
```
datadog {
site = "US"
checkProjectDependencies = "fail"
variants {
fr {
site = "EU"
checkProjectDependencies = "none"
}
}
}
```
Get a better feedback to the Datadog SDK user if setup is wrong.
Check is done at the pre-compilation …

RUMM-1010: Warn or fail the build when Datadog SDK is missing in the project dependencies

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/VariantIterator.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/VariantIteratorTest.kt
samples/variants/build.gradle

Let customer define plugin configuration with partial variant names. 
This uses the same priority as the one defined in the Android compiler when resolving Source Sets.

RUMM-1103 handle partial variant configurations

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-gradle-plugin/transitiveDependencies
samples/basic/build.gradle
samples/variants/build.gradle

Better version of #19. It takes advantage of Gradle 6.8.3 shipped with embedded Kotlin version 1.4.20 (originally update was done here https://github.com/gradle/gradle/commit/b5f89f1a7c1accc84806751c2c8941fae43cd33a to 1.4.10 and then also here https://github.com/gradle/gradle/commit/6f634d19a5bf4cb21af1ed9b2bffe3089a33efc3 to 1.4.20).
With Kotlin 1.4 there is no need to declare `stdlib` explicitly, it is added automatically: https://kotlinlang.org/docs/gradle.html#dependency-on-the-standard-library (so I removed it in the `buildSrc`, but kept in the individual build scripts, just in case).
More on embedded Kotlin: https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin

Use embedded Kotlin for the build script, bump Kotlin version to 1.4.20

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt

This change prevents listing patterns mentioned in `.gitignore` by switching from manual folder traversal to using [git ls-files](https://git-scm.com/docs/git-ls-files) which respects this rule.

RUMM-1115: Prevent listing git ignored files

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt

The Maven plugin creates a publication automatically for jar outputs with the relevant dependencies.
Instead of creating a "blank" publication, we can reuse the existing one and add the missing info there.

Fix POM file missing dependencies

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/VariantIteratorTest.kt

This change fixes flaky test in the case when one variant name contains another variant name. This makes assertion fail and I didn't find a good way to fix it at the assertion level, so let's apply more rules to the input.

Fix flaky VariantIterator test when one variant can contain another variant name

---

LICENSE-3rdparty.csv
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-gradle-plugin/build.gradle.kts
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/RepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/ProjectExt.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt
dd-sdk-android-gradle-plugin/transitiveDependencies

This change adds support of configuration cache. Currently, if we run task with `--configuration-cache` flag, the following errors happen claiming it cannot serialize task:
1. Execution of upload task:
```
value NativePRNG failed Java Object Serialization
field secureRandom of sun.security.ssl.SSLContextImpl$TLSContext
bean of type sun.security.ssl.SSLContextImpl$TLSContext
field context of sun.security.ssl.SSLSocketFactoryImpl
bean of type sun.security.ssl.SSLSocketFactoryImpl
field sslSocketFactory of okhttp3.OkHttpClient
bean of type okhttp3.OkHttpClient
field client of com.datadog.gradle.plugin.internal.OkHttpUploader
bean of type com.datadog.gradle.plugin.internal.OkHttpUploader
field uploader of com.datadog.gradle.plugin.DdMappingFileUploadTasktask:samples:variants:uploadMappingFullR …
```

RUMM-1451: Support Gradle configuration cache

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesTask.kt
dd-sdk-android-gradle-plugin/build.gradle.kts
dd-sdk-android-gradle-plugin/transitiveDependencies

This change remove Gradle API from dependencies, because it is automatically added by `java-gradle-plugin` as stated in the https://docs.gradle.org/current/userguide/custom_plugins.html#sec:custom_plugins_standalone_project:
> The easiest and the recommended way to package and publish a plugin is to use the Java Gradle Plugin Development Plugin. This plugin will automatically apply the Java Plugin, add the gradleApi() dependency to the api configuration, generate the required plugin descriptors in the resulting JAR file and configure the Plugin Marker Artifact to be used when publishing.
Moreover, in the end `gradleApi` is added as `api` dependency (https://github.com/gradle/gradle/blob/cb232651cd8fd2856f76e651d397b301c9b42936/subprojects/plugin-development/src/main/java/org/gradle/plugin/ …

Remove Gradle API from dependencies

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/sanitizer/FullUriGitRemoteUrlSanitizer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/sanitizer/GitRemoteUrlSanitizer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/sanitizer/ShortUriGitRemoteUrlSanitizer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/sanitizer/UriParsingException.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/sanitizer/UrlSanitizer.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/sanitizer/GitRemoteUrlSanitizerTest.kt

There were reported situations when the client was using an `HTTPS` Git Remote URL which contained also the `username` and `password`: `https://username:password@github.com/username/repository.git`. In this case we were uploading the full URL together with the `mapping.txt` file to our DD servers.
In this PR we are sanitizing the URL and we remove the user information if any.

RUMM-1411 Remove credentials if any from GIT remote URL

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/RepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionConfigurationForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetectorTest.kt
docs/upload_mapping_file.md

This **PR** adds the capability to be able to set the GIT remote URL of your source code  through the `dd-sdk-android-gradle-plugin` extension. This property is optional in the plugin extension and if not provided will be resolved from the user's GIT configuration during the `uploadMapping` task execution.

RUMM-1412 Add remote repository URL into the plugin extension

---

.gitlab-ci.yml

Without the fix Maven URL is wrong - it is missing tag.

Fix Maven URL in the Slack notification message

---

README.md

Follow-up for the change https://github.com/DataDog/dd-sdk-android-gradle-plugin/pull/40, adds an explanation about Gradle configuration cache support to `README`. Should be merged only after `1.1.0` is published.

Add a note about Gradle configuration cache support to README

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/RepositoryInfo.kt

This change is similar to DataDog/dd-sdk-android#704, removes Bintray/JCenter repo references and updates libs which were hosted there before.

RUMM-1622: Remove Bintray/JCenter repo references

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/GitRepositoryDetector.kt
samples/basic/build.gradle

Ensure git files are reported with full path from repo root.
In some cases the `cwd` is not the repo root, meaning that the path we get from `git ls-files` are not correct. Adding the `--full-name` forces git to report the paths from the repo root.

RUMM-1795 Ensure git files are reported with full path from repo root

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt

Delay the android extension check.
In some cases, the order in which plugins are applied doesn't match the order in the `plugins { }` block, meaning that the Datadog plugin can be started before the Android one is applied, meaning the extension is not there yet. Delaying it ensures the plugin gets applied properly

RUMM-1778 delay the android extension check

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt

Fixes #62. The problem comes in the multi-module setup, when there is module `A` with some flavors (say `foo` and `bar`) which is using another module `B` without mentioned flavors.
Because the way task execution works, gradle tries to unwrap `Configuration` input, but it fails to do that, because there is no 1:1 match between `A` and `B` configurations (but AGP itself is able to match them, because it applies fallback).
This change proposes to use configuration name instead in the input, so that it can be later pulled from the configurations list (using `project` in the task is not compatible with configuration cache, but using `Configuration` in the input is not compatible as well, so we don't break anything from this point).
Because now inputs don't change if configuration itself is …

RUMM-1824: Fix dependency check task crash in the multi-module setup

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionConfigurationForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionForgeryFactory.kt

Adds a new property for the plugin extension configuration -> `mappingFilePath`. Using this new property users will be able to provide their own custom `mappingFilePath` for each application variant in case they are using any other third party code obfuscator than the default one.
Close issue #71 

RUMM-1972 Provide mappingFilePath through plugin configuration

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

This change brings support of AGP 7.1: it renamed compilation tasks and the task we were relying on is still there, but it is not a part of build process.

RUMM-1954: Support AGP 7.1.x

---

docs/upload_mapping_file.md

This change adds a section to the docs explaining that upload mapping task is not a part of the default build graph by default (it means it needs to be run manually once mapping file is generated, unlike for `Crashlytics`, for example) and adds a code example on adding it to the default build graph.

RUMM-1845: Add a note to the docs that upload mapping task is not a part of the default build graph

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt

Adapt the payload format to API v2
Stay compatible with the backend processor evolutions

RUMM-2342 Add support to v2 request

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_set_to_warn.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle

This change disables SDK check in the dependencies by default, to avoid false positive errors in certain setups.
We will come back to this check later in RUMM-2344.
Temporarily fixes https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/85.

RUMM-2163: Disable dependencies check task by default

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DatadogSite.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/ApiKey.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionConfigurationForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdExtensionForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
docs/upload_mapping_file.md

This change supports parsing some properties from `datadog-ci.json`, namely `datadogSite` and `apiKey` properties.
This file may be located in the root of the project (but since the definition of the root may vary between the different setups, we try to find `datadog-ci.json` file by doing upward traversal).
The order of API key lookup is like the following:
* Gradle property
* `datadog-ci.json` file
* Environment property
The order of site lookup is like the following:
* Gradle extension configuration
* `datadog-ci.json` file
`datadog-ci.json` file is included as an input of upload task so that it can be watched by the Gradle for the changes, otherwise it won't be checked and any changes there won't be reflected when running upload task, which may be confusing for the user.

RUMM-2345: Read config properties from datadog-ci.json

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
docs/upload_mapping_file.md

Enable reading site from `DATADOG_SITE` and api key from `DATADOG_API_KEY`
Harmonizing env variable names across the Gradle plugin and datadog-ci

RUMM-2346 Add more environment variables

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/transitiveDependencies

Fixes #111. `currentDir` had an implicit type `File` inherited from the `projectDir` argument, but because `parentFile` can return `null`, conversion to `File` failed.

RUMM-2469: Fix a possible NPE in the datadog-ci.json file lookup

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating from version 1.14.0-beta1 to version 1.14.0-beta2: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.14.0-beta1...1.14.0-beta2)

Update to version 1.14.0-beta2

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating from version 1.15.0 to version 1.16.0-beta1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.15.0...1.16.0-beta1)

Update to version 1.16.0-beta1

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DatadogSite.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/Uploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/RecordedRequestAssert.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This change improves mapping upload flow handling by doing the following:
* Additional check for the API key validity is done (using [API key validation API](https://docs.datadoghq.com/api/latest/authentication/#validate-api-key)) if server returns code 400, this is basically aligns logic with [datadog-ci](https://github.com/DataDog/datadog-ci/blob/ffc52ea6c0b0ac44004544bf84689a22ce2d4119/src/helpers/apikey.ts#L48).
* Removed a statement saying that server may already have mapping uploaded - server will never return error if there is already mapping uploaded.
* Added an additional check for quotes\apostrophes in API key, this may be useful for the error investigation on the client side (this check is quite limited to only quotes and apostrophes, because there is no public contract for the …

RUMM-2770: Improve mapping upload flow handling

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/Uploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/RecordedRequestAssert.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt

This change add Gzip support for mapping file upload by optionally (enabled by default) adding gzip encoding to the `srcmap` endpoint request.
There is a way to disable this behavior by using `dd-disable-gzip` Gradle property. This property is accessed using `ProviderFactory#gradleProperty`, which is available since Gradle 6.2 (but we are using already `ExecOperations` interface for a long time which is available since Gradle 6.0, so it should be ok to bump min Gradle version a bit).
Unfortunately it is not possible to test this property using unit tests (because `org.gradle.testfixtures.ProjectBuilder` used in the `DdMappingFileUploadTaskTest` is not capable of reading/setting Gradle properties), so I had to rely on the functional tests instead.

RUMM-2952: Add Gzip support for mapping file upload

---

docs/upload_mapping_file.md

Improve the documentation to give workarounds when the mapping file is above 50 Mb

Improve the documentation for 50Mb limit

---

gradle/libs.versions.toml

Updating from version 1.17.1 to version 1.17.2: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.17.1...1.17.2)

Update to version 1.17.2

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating from version 1.17.2 to version 1.18.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.17.2...1.18.0)

Update to version 1.18.0

---

build.gradle.kts
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/DdAppIdentifier.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTaskTest.kt

Ensure the message about upload "success" is always visible when running the upload task

RUMM-3398 Improve output of gradle plugin upload

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating from version 2.0.0-beta1 to version 2.0.0-beta2: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.0.0-beta1...2.0.0-beta2)

Update to version 2.0.0-beta2

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating from version 2.0.0-beta2 to version 2.0.0-beta3: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.0.0-beta2...2.0.0-beta3)

Update to version 2.0.0-beta3

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

This PR does update of ~~Gradle version to 8.2.1~~ (removed from PR, see bug https://youtrack.jetbrains.com/issue/KT-60748) and also updates AGP version to 8.1.0.

RUMM-3487: Update AGP to 8.1.0

---

gradle/libs.versions.toml

Updating from version 2.0.0-beta3 to version 2.0.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.0.0-beta3...2.0.0)

Update to version 2.0.0

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating Datadog SDK from version 2.0.0 to version 2.1.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.0.0...2.1.0)

Update Datadog SDK to version 2.1.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt

There is a bug that old shrinked mapping file wasn't deleted before doing the shrinking again. This PR fixes it.

RUM-1052: Delete old shrinked mapping file before writing to it

---

gradle/libs.versions.toml

Plugin version `1.11.0` is already released, we can reference it for the usage in sample apps.

Use plugin version `1.11.0` for sample apps

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating Datadog SDK from version 2.1.0 to version 2.2.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.1.0...2.2.0)

Update Datadog SDK to version 2.2.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt

Lower log level from warning to info when no minification enabled

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/build_with_non_default_obfuscation.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_plugin_disabled.gradle

Adds a `nonDefaultObfuscation` option in the extension for our plugin. This will create an uploadTask even if the Android `minifyEnabled` option is `false`
Among others, Dexguard users are not using Android's `minifyEnabled` which relies on the default R8/Proguard obfuscation.  For those users, the upload task wasn't created even on variants using DexGuard who needed it. 
Fixes #132 
```
datadog {
nonDefaultObfuscation = true
mappingFilePath = "custom/path/to/mapping.txt"
}
```

RUM-713 Allow customer to use non standard obfuscation

---

CHANGELOG.md

This PR does the merge of `release/1.12.0` branch into `develop` branch with conflicts resolved.

Merge `release/1.12.0` branch into `develop` branch

---

gradle/libs.versions.toml

After the release of `1.12.0` of Gradle Plugin we can reference it for the sample apps.

Use version 1.12.0 of plugin for sample apps

---

dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_non_default_obfuscation.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_plugin_disabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
gradle/libs.versions.toml

Updating Datadog SDK from version 2.2.0 to version 2.3.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.2.0...2.3.0)

Update Datadog SDK to version 2.3.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdCheckSdkDepsTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/GenerateBuildIdTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/DdAppIdentifier.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/IdentifierForgeryFactory.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt

This PR brings support of so-called build ID, which will allow us to precisely match stacktrace sent to Datadog with a mapping file.
This is achieved by generating build ID with each build, so that it can be added to the mapping file upload metadata and also stored as a file in the `assets` folder of the application which is going to be built, so that it can be later read by the SDK in runtime and added to the RUM/Logs errors.

RUM-1822: Inject build ID into mapping file upload and SDK host application as well

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/JUnitConfig.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_disabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_check_deps_set_to_warn.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_custom_remote_repos_url.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_lib_module_attached.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_minify_not_enabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_non_default_obfuscation.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_optimized_mapping.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_plugin_disabled.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_with_variant_override.gradle
dd-sdk-android-gradle-plugin/src/test/resources/build_without_datadog_dep.gradle
dd-sdk-android-gradle-plugin/src/test/resources/lib_module_build.gradle

Because of the way [GradleRunner#withPluginClasspath](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath--) works we were actually running E2E tests always with the AGP version plugin was compiled against.
This PR fixes it, now we will run tests for AGP 7.0.4 and AGP 8.2.0.
Also few issues were discovered thanks to the proper test runs, and they are fixed with this PR as well.

RUM-2451: Run functional tests against different AGP versions

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.3.0 to version 2.4.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.3.0...2.4.0)

Update Datadog SDK to version 2.4.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.4.0 to version 2.5.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.4.0...2.5.0)

Update Datadog SDK to version 2.5.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.5.0 to version 2.5.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.5.0...2.5.1)

Update Datadog SDK to version 2.5.1

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.5.1 to version 2.6.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.5.1...2.6.0)

Update Datadog SDK to version 2.6.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.6.1 to version 2.6.2: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.6.1...2.6.2)

Update Datadog SDK to version 2.6.2

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt

Extra attributes were printed but then ignored by the OkHttpUploader, when they should have been added to the event.

fix: Ensure extra attributes are placed on events

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.6.2 to version 2.7.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.6.2...2.7.0)

Update Datadog SDK to version 2.7.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.7.0 to version 2.7.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.7.0...2.7.1)

Update Datadog SDK to version 2.7.1

---

.editorconfig
.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/SPDXLicense.kt
samples/basic/src/main/java/com/datadog/example/basic/MainActivity.kt

This PR updates the version of static analysis pipeline used to `v25558398-8517309a`.

Update version of static analysis pipeline used

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt

This PR prepares release 1.13.0. It includes commit to skip NDK symbol files upload task creation, because this functionality is not yet completely ready on the backend side, so shouldn't be a part of the release.

Prepare release 1.13.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.7.1 to version 2.8.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.7.1...2.8.0)

Update Datadog SDK to version 2.8.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt

This PR switches to the lazy configuration of upload task by using `TaskContainer#register` API instead of `TaskContainer#create`. This solves the problem of compatibility with https://github.com/Triple-T/gradle-play-publisher plugin which is similar to what described here https://github.com/Triple-T/gradle-play-publisher/issues/940.
Long-term solution will be to switch from the legacy Variant API to the new Variant API.
**Note**: This is a partial fix, because if both tasks try to configure themselves in the same build execution, the problem will still occur. But it is not clear if it should be fixed on our side or problem is on the `gradle-play-publisher` plugin side.

RUM-4031: Avoid eager fetching of Variant values

---

gradle/libs.versions.toml

This PR updates Datadog Gradle Plugin version used for the sample files to 1.13.1.

Use Datadog Gradle Plugin 1.13.1 for samples

---

.gitlab-ci.yml
Dockerfile.gitlab

This PR migrates Docker images to the GBI images (Golden Base Image) which are owned by Datadog.

Migrate to GBI images

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdNdkSymbolFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdNdkSymbolFileUploadTaskTest.kt

The symbolication service currently understands `arm`, `arm64`, `x86` and `x64` as valid symbol file architectures. Instead of adding the Android ABIs, we map them to those architectures instead.

fix: Standardize architectures

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.8.0 to version 2.9.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.8.0...2.9.0)

Update Datadog SDK to version 2.9.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/Uploader.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdMappingFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdNdkSymbolFileUploadTaskTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploaderTest.kt

Right now we are calling the real intake for the functional tests of Gradle Plugin, and since we don’t have a real API key, we get an error and we expect build failure in our tests. However, it may be some other build failures, so it is handy to emulate network call to make test expectation without any build failures.
This PR adds build parameter `dd-emulate-upload-call` which can be passed for the build script execution. If it is present, no real network call will be made and we will create a fake response.

RUM-4374: Emulate upload network call for functional tests

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdTaskUtils.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt

This PR will mark upload task as not compatible with configuration cache, meaning it won't be recorded for the configuration cache.
This fixes the issue #251.
Note, that we may come back to the configuration cache support for this task in the future, but for now the issue is that task input expects build ID file to be present, and it will be present only after build run, not at the configuration phase. Complete configuration cache support thus will require major logic changes, which may be not worth it, considering that configuration for this task is very fast.

RUM-4292: Mark upload task as not compatible with configuration cache

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdNdkSymbolFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginTest.kt

This PR will make build ID generation task to be created only if there is obfuscation enabled or there are native build providers.
Partially addresses #258.

RUM-4406: Avoid BuildId task creation if there is no obfuscation or native build providers registered

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/OkHttpUploader.kt

This PR increases the upload timeout limit from 60s to 120s in all DCs. This change was made in order to support customers with slower upload speeds. 

[RUM-4594] Increase upload timeout to 120s to match EvP limits

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.9.0 to version 2.10.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.9.0...2.10.0)

Update Datadog SDK to version 2.10.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/CurrentAgpVersion.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/variant/AppVariant.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/variant/LegacyApiAppVariant.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/internal/variant/NewApiAppVariant.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/internal/variant/LegacyApiAppVariantTest.kt

This PR makes to use `Variant.mappingFileProvider` in case of legacy API usage. This brings more reliable way to get a mapping file.

Use mapping file provider in case of legacy Variant API

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/build_with_android_components.gradle

This PR adds the necessary test to reproduce the issue mentioned in #242 and #257. The problem itself was fixed in #263.

RUM-4407 & RUM-4087: Add test for the duplicate resources issue with AGP 8.4.x

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.10.0 to version 2.10.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.10.0...2.10.1)

Update Datadog SDK to version 2.10.1

---

README.md

We support deobfuscation for logs for a long time already, so removing false statement.

Remove the statement from `README` that logs are not deobfuscated

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.10.1 to version 2.11.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.10.1...2.11.0)

Update Datadog SDK to version 2.11.0

---

README.md

Add an `Uploading` section for the README which includes instructions for uploading mapping files and NDK symbol files

Add uploading section to README.

---

gradle/libs.versions.toml

Updating Datadog SDK from version 2.11.0 to version 2.12.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.11.0...2.12.0)

Update Datadog SDK to version 2.12.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.12.0 to version 2.12.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.12.0...2.12.1)

Update Datadog SDK to version 2.12.1

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.12.1 to version 2.13.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.12.1...2.13.0)

Update Datadog SDK to version 2.13.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.13.0 to version 2.13.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.13.0...2.13.1)

Update Datadog SDK to version 2.13.1

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.13.1 to version 2.14.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.13.1...2.14.0)

Update Datadog SDK to version 2.14.0

---

gradle/libs.versions.toml

Updating Datadog SDK from version 2.14.0 to version 2.15.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.14.0...2.15.0)

Update Datadog SDK to version 2.15.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.15.0 to version 2.15.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.15.0...2.15.1)

Update Datadog SDK to version 2.15.1

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.16.0 to version 2.16.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.16.0...2.16.1)

Update Datadog SDK to version 2.16.1

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.16.1 to version 2.17.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.16.1...2.17.0)

Update Datadog SDK to version 2.17.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/NdkSymbolFileUploadTask.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
dd-sdk-android-gradle-plugin/src/test/resources/native_gradle_files/build_with_custom_ndk.gradle
dd-sdk-android-gradle-plugin/src/test/resources/native_gradle_files/build_with_custom_ndk_no_externalNativeBuild.gradle

Adds a property `additionalSymbolsFilesLocations ` which allows to specify custom .so files location in order to upload them with **uploadNdkSymbolFiles** task
This is the response to customer [request](https://github.com/DataDog/dd-sdk-android-gradle-plugin/issues/296)

RUM-7461: supporting custom ndk symbols path

---

.gitlab-ci.yml

`test:plugin` keeps failing on CI with this error:
```
> Task :dd-sdk-android-gradle-plugin:test
DdAndroidGradlePluginFunctionalTest > M success W assembleRelease() FAILED
java.lang.IllegalStateException at DdAndroidGradlePluginFunctionalTest.kt:142
Caused by: org.gradle.tooling.GradleConnectionException at DdAndroidGradlePluginFunctionalTest.kt:142
Caused by: org.gradle.launcher.daemon.client.DaemonDisappearedException at DaemonClient.java:283
DdAndroidGradlePluginFunctionalTest > M not try to upload the symbol file W no cmake dependencies { using a fake API_KEY }() FAILED
java.lang.IllegalStateException at DdAndroidGradlePluginFunctionalTest.kt:1022
Caused by: org.gradle.tooling.GradleConnectionException at DdAndroidGradlePluginFunctionalTest.kt:1022
Caused by: …
```

Overwrite gradle.properties with CI configs for test plugin task

---

.gitlab-ci.yml

Increase CI kubernetes memory limit to 20Gi .
To avoid `test:plugin` task triggering OOM on CI
The previous fix of adding the override of gradle.properties is revoked.

Increase CI kubernetes memory limit to 20Gi to avoid OOM

---

dd-sdk-android-gradle-plugin/build.gradle.kts
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt

Prior to this PR, in the sample app we need to use `kotlinCompilerPluginClasspath` to make KCP work during the kotlin compilation.
```
dependencies{
kotlinCompilerPluginClasspath("com.datadoghq:dd-sdk-android-gradle-plugin:$version")
}
```
The goal of this PR is that KCP can be automatically registered after client apply our AGP in the `plugins{}`block:
```
plugins{
id("com.datadoghq.dd-sdk-android-gradle-plugin")
}
```
The idea of this PR is to apply compilerOptions programatically from our AGP class
```
android {
...
kotlin {
compilerOptions {
freeCompilerArgs.add(
"-Xplugin=/path/to/kotlin-compiler-plugin.jar"
)
}
}
```
The step to achieve it:
* find plugin "org.jetbrains.kotlin.android" and configure insdie.
* Retrieve the "dd-sdk-android-gradle-plugin" version declared in root gradle …

RUM-8838: Register Kotlin compiler plugin to Kotlin compile options

---

LICENSE-3rdparty.csv
dd-sdk-android-gradle-plugin/build.gradle.kts
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/KotlinCompilerTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/TestCallbackContainer.kt
gradle/libs.versions.toml

In this PR, [Kotlin compile testing](https://github.com/tschuchortdev/kotlin-compile-testing) library is introduced to test the compilation result when datadog kotlin compiler plugin is applied.
The idea is to have a stub `DatadogModifier`, this stub one has the same path and function signature so that our KCP will be able to find it and inject it. 
Also for each case we have an example class with `@Composable` to verify that the injection will work in different use cases:
* No modifier is provided
* Default `Modifier` is provided
* Custom modifier is provided.
A `TestCallbackContainer` is introduced to store the mock callback passed from the test environment. The verification process consists of the following steps:
* Load the `TestCallbackContainer` object using the compilation result’s …

RUM-8876: Add Kotlin compilation unit test for modifier injection

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/MappingFileUploadTask.kt

Small improvement for the [mappingFilePackageAliases](https://github.com/DataDog/dd-sdk-android-gradle-plugin/blob/ad67028439931bb4608d2a94768641f5f2c56e4e/dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt#L76) configuration usage: since keys are used in the regex, `.` can be interpreted as any symbol and users may also include `.*` as a wildcard.
This PR threatens the former as a literal instead of being meta sequence and ignores the latter (since keys are supposed to be the prefixes).
This should speed up algorithm a bit on the large files.

RUMS-4053: Escape user input for mapping file packages aliases

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/MappingFileUploadTask.kt

Mapping file can read few hundred MBs and so this PR improves its handling in such case by:
* Using buffered writing to the disk instead of doing I/O operation for each line
* Avoiding loading the whole file in the memory and using the stream to read the file line by line.

RUM-8910: Improve big mapping file handling in the shrinking process

---

dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/NavController.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/NavDestination.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/NavHostController.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/compose/NavGraphBuilder.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/compose/NavHost.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/navigation/compose/NavHostController.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt

According to the [task](https://datadoghq.atlassian.net/browse/RUM-8878), we are supposed to instrument `com.datadog.android.compose.NavigationViewTrackingEffect` function into `NavHost` of client code.
Before jumping into the implementation of instrumentation, this PR sets up unit tests to cover the necessary use cases.
* `KotlinCompilerTest` is used to test for compose tag instrumentation, now it becomes a base class providing compilation and execution test functions.
* `ComposeTagCompilationTest` extends from `KotlinCompilerTest` and contains the test cases of tag instrumentation migrated from old `KotlinCompilerTest` .
* `ComposeNavHostCompilationTest` extends from `KotlinCompilerTest` and contains the test case for NavHost instrumentation.
* Several fake classes are introduced, they …

RUM-8952: Setup Kotlin compiling test for NavHost injection

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdExtensionConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/InstrumentationMode.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DatadogIrExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DatadogKotlinCompilerPluginCommandLineProcessor.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DatadogPluginRegistrar.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/InstrumentationConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/InternalCompilerConfiguration.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerPluginOptions.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/DatadogIrExtensionTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/DatadogKotlinCompilerPluginCommandLineProcessorTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/forge/Configurator.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/utils/forge/InternalCompilerConfigurationFactory.kt

This PR implements the DSL config for auto instrumentation, so that clients can define the config like:
```
datadog{
composeInstrumentation{
trackViews =  InstrumentationMode.AUTO
trackActions =  InstrumentationMode.ANNOTATION
recordImages =  InstrumentationMode.DISABLE
}
}
```
RUM-8950

RUM-8950: Implement Kotlin compiler plugin DSL configuration

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DatadogPluginRegistrar.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostExtensionTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagExtensionTest.kt

`ComposeTagTransformer` and `ComposeNavHostTransformer` needs to perform in different stages of Kotlin IR.
`ComposeNavHostTransformer` needs to execute **before** Compose Compiler plugin, so that our `@composable` function injected into client code can be instrumented by Compose Compiler plugin.
`ComposeTagTransformer` needs to be execute **after** Compose Compiler plugin, so that embedded composable block will be lowered to flat java functions, for visiting calls, it's easier to scan out all the modifiers.
With that purpose, `DatadogIrExtension` is separated to two to register extensions respectively.

Separate compose extension to register respectively

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.19.0 to version 2.19.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.19.0...2.19.1)

Update Datadog SDK to version 2.19.1

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagTransformer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DefaultPluginContextUtils.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/PluginContextUtils.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/compose/foundation/Image.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/androidx/compose/material/Icon.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/coil/compose/AsyncImage.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/TestCallbackContainer.kt
samples/lib-module/src/main/kotlin/com/datadog/kcp/compose/DatadogModifier.kt

In dd-sdk-android, Session Replay Compose resolves the components differently based on the Semantics Role.
Prior to this PR, `datadog` modifier only add semantics tag to help the components merged into the tree, but Images still don't have a `Role` since the `contentDescription` can be absent.
This PR enriches the `datadog` modifier with a new argument `isImageRole: Boolean`, and kotlin compiler plugin will sca the component for `Image`, `Icon` or `AsyncImage`, then put `true` on this argument to append semantics role for the components.
RUM-9088

RUM-9088: Add semantics role for Image, Icon and AsyncImage

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagTransformer.kt
instrumented/src/androidTest/java/com/datadog/android/instrumented/SemanticsTest.kt

Currently we use `DD_DEFAULT_TAG` as semantics tag value for all the nodes, 
In this PR, we detect the composable function name of the expression, and use it as the value of the semantics tag.
For example, in the client code if they have:
```
Column{
Image(painter = xx, contentDescription = null)
Text(text = "something")
CustomView()
}
```
In the semantics tree it will have:
```
|-Node #16 
| _dd_semantics = 'Column'
|  |-Node #48 
|     | _dd_semantics = 'Image'
|  |-Node #49
|     | _dd_semantics = 'Text'
|  |-Node #50
|     | _dd_semantics = 'CustomView'
```

RUM-8813: Use composable function name as the semantics tag

---

instrumented/build.gradle.kts
instrumented/src/androidTest/java/com/datadog/android/instrumented/NavigationTest.kt
instrumented/src/main/java/com/datadog/android/instrumented/NavHostTestScreen.kt

Add instrumented test for view trackings instrumentation, the test verifies two things:
* The instrumentation doesn't break client's code. (the original components should still be present on the screen after instrumentation)
* The function that we instrumented takes effect. (`NavigationViewTrackingEffect` registers listener inside the `navController`, so we use reflection to verify that navController's listener size)
RUM-8953

RUM-8953: Add Instrumented test for view trackings instrumentation

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostTransformer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagExtension.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagTransformer.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DefaultPluginContextUtils.kt
dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/PluginContextUtils.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeNavHostCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagCompilationTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/ComposeTagTransformerTest.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
samples/lib-module/src/main/kotlin/com/datadog/kcp/compose/RecordImages.kt
samples/lib-module/src/main/kotlin/com/datadog/kcp/compose/TrackViews.kt

* Add annotations class `RecordImages` and `TrackViews` in `samples/lib-module` to simulate the real implementation in sdk.
* In `ComposeNavHostTransformer` and `ComposeTagTransformer`, filter in the annotated functions if annotation mode is enabled, and instrument only for these functions
RUM-9011

RUM-9011: Implement annotation mode for instrumentation

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/IrExt.kt

The Kotlin compiler plugin relies on `Kotlin-embeddable` for Intermediate Representation phase, 
when plugin is running in the host application during the compilation,  the Kotlin version from Android Gradle Tool will override the one in plugin during the runtime. 
For example, if the Android Gradle Tool version is "8.8.2", the kotlin "1.9.24" version from it will be actually used during the runtime of the plugin despite "2.0.20" is declared in the plugin project. And since it's a major version change, it leads some binary compatibility issue which makes build failed.
The main idea of this PR is to check the known broken API version, by checking function signature, visibility, etc.. to instantiate it by reflection if we find it's not compatible with the compilation version.
Here is a list …

Enhance compiler plugin binary backward compatibility

---

gradle/libs.versions.toml

Updating Datadog Gradle Plugin from version 1.15.0 to version 1.16.0: [diff](https://github.com/DataDog/dd-sdk-android-gradle-plugin/compare/1.15.0...1.16.0)

Update Datadog Gradle Plugin to version 1.16.0

---

dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/kcp/DefaultPluginContextUtils.kt
dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/kcp/KotlinCompilerTest.kt
instrumented/build.gradle.kts
instrumented/src/androidTest/java/com/datadog/android/instrumented/NavigationTest.kt
instrumented/src/androidTest/java/com/datadog/android/instrumented/SemanticsTest.kt
samples/lib-module/src/main/kotlin/com/datadog/android/compose/DatadogModifier.kt

Reference changes based on the [ PR ](https://github.com/DataDog/dd-sdk-android/pull/2601)
* `datadog` -> `instrumentedDatadog`
* `NavigationViewTrackingEffect` -> `InstrumentedNavigationViewTrackingEffect`
Because `Instrumented` module depends on the release version of SDK for instrumented test, so it can not find the `InstrumentedNavigationViewTrackingEffect` API in current version of SDK, we need to wait to restore it until the API goes to public.

Update Compose Instrumentation functions references

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

Updating Datadog SDK from version 2.20.0 to version 2.21.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/2.20.0...2.21.0)

Update Datadog SDK to version 2.21.0

---

gradle/libs.versions.toml

Updating Datadog Gradle Plugin from version 1.16.0 to version 1.17.0: [diff](https://github.com/DataDog/dd-sdk-android-gradle-plugin/compare/1.16.0...1.17.0)

Update Datadog Gradle Plugin to version 1.17.0

---

dd-sdk-android-gradle-plugin/src/test/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePluginFunctionalTest.kt
gradle/libs.versions.toml

This PR updates regular Datadog SDK version used to `2.23.0`, and snapshot version to `2.24.0-SNAPSHOT`.

Update Datadog SDK version to 2.23.0

---

.github/chainguard/all.gitlab.pr.sts.yaml
.github/chainguard/self.gitlab.read.sts.yaml
.gitlab-ci.yml
Dockerfile.gitlab

I need to introduce `dd-octo-sts` to this repo the same way I did in `dd-sdk-android`. In this pr:
1. Added `dd-octo-sts` to the Docker image.
2. Changed `all.gitlab.pr.sts.yaml` to also allow pr creation from `dd-sdk-android-gradle-plugin`. Needed [here](https://github.com/DataDog/dd-sdk-android-gradle-plugin/blob/develop/.gitlab-ci.yml#L250).
3. Added `self.gitlab.read.sts.yaml` - policy to read `dd-sdk-android-gradle-plugin`. It will be used when I create a pipeline to check the release similar to [this](https://github.com/DataDog/dd-sdk-android/blob/develop/ci/pipelines/check-release-pipeline.yml).

RUM-10224: Add dd-octo-sts to docker image and add policy yamls

---

gradle/libs.versions.toml

Updating Datadog Gradle Plugin from version 1.17.0 to version 1.18.0: [diff](https://github.com/DataDog/dd-sdk-android-gradle-plugin/compare/1.17.0...1.18.0)

Update Datadog Gradle Plugin to version 1.18.0

---

dd-sdk-android-gradle-plugin/build.gradle.kts
gradle/libs.versions.toml

Configure gradle file to create multiple source sets for Compiler Plugin.
This is the first step for adding the compatibility for different versions of Kotlin.
RUM-11238

Configure gradle file to create multiple source sets for Compiler Plugin

---

buildSrc/build.gradle.kts
dd-sdk-android-gradle-plugin/build.gradle.kts
dd-sdk-android-gradle-plugin/transitiveDependencies
gradle/libs.versions.toml

Prior to this PR, we use Kotlin 2.0.21 for the whole project, when compiling the `kotlin22` source set, the compiler will throw the error saying:
> Class 'org.jetbrains.kotlin.backend.common.extensions.FirIncompatiblePluginAPI' was compiled with an incompatible version of Kotlin. The actual metadata version is 2.2.0, but the compiler version 2.0.0 can read versions up to 2.1.
Then we have to add following argument to the compiler to let it pass:
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
kotlinOptions {
freeCompilerArgs += "-Xskip-metadata-version-check"
}
}
```
To remove this, we need to upgrade Kotlin compiler version to 2.1.x.
RUM-11262

RUM-11262: Upgrade Kotlin Version to 2.1.21 to remove metadata check error
